version: "3"

services:
  my-notes-db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mynotes
      - PG_DATA=/var/lib/postgresql12/data
    volumes:
      - postgresql:/var/lib/postgresql12
      - postgresql_data:/var/lib/postgresql12/data
    restart: always
    networks:
      - my-notes-net
  my-notes-service:
    image: andrbezr2016/my-notes-app:1.0
    ports:
      - 8081:8081
    environment:
      - POSTGRES_PATH=jdbc:postgresql://my-notes-db:5432/mynotes
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    depends_on:
      - my-notes-db
    restart: always
    networks:
      - my-notes-net
  my-notes-client:
    image: andrbezr2016/my-notes-front:1.0
    ports:
      - 8080:8080
    networks:
      - my-notes-net
volumes:
  postgresql:
  postgresql_data:
    driver: local

networks:
  my-notes-net:
    driver: bridge
