spring:
  name: my-notes
  datasource:
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5432/mynotes}
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    com.andrbezr2016.mynotes: DEBUG